---
- hosts: all

  roles:
    - { role: jdauphant.nginx, become: yes }
    - {role: williamyeh.oracle-java, become: yes }
    - sbt
    - {role: nodejs, become: yes }
    - {role: system, become: yes}
    - project
    - {role: letsencrypt, become: yes, when: is_production}
    - {role: production, become: yes, when: is_production}

  vars:
    is_production: false
    project_ssh_key: ~/.ssh
    project_back_port: 8080
    project_back_repository: git@github.com:thymeflow/thymeflow-back.git
    project_back_root: "{{ ansible_env.HOME }}/repositories/thymeflow-back"
    project_back_version: v0.1.0
    project_front_repository: git@github.com:thymeflow/thymeflow-front.git
    project_front_root: "{{ ansible_env.HOME }}/repositories/thymeflow-front"
    project_logs_path: "{{ ansible_env.HOME }}/logs"
    project_front_version: v0.1.0
    nginx_events_params:
     - worker_connections 512
     - use epoll
     - multi_accept on
    java_version: 8
    java_subversion: 102
    sbt_version: 0.13.12
    nodejs_version: 6.x
    npm_config_prefix_bash: "$HOME/.npm-global"
    npm_config_prefix: "{{ ansible_env.HOME }}/.npm-global"
    global_nodejs_dependencies:
      - name: bower
      - name: ember-cli
        version: 2.6.3
    nginx_sites:
      default:
        - listen 80 default_server
        - server_name _
        - return 444

  vars_files:
    - application.yml