---
- name: Install NodeJS repository
  shell: curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
  args:
    creates: /etc/apt/sources.list.d/nodesource.list

- name: Install NodeJS
  shell: apt-get install --yes nodejs
  args:
    creates: /usr/bin/npm
